// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akxqacrhjkfancasjfql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFreHFhY3JoamtmYW5jYXNqZnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjM1ODAsImV4cCI6MjA2NjgzOTU4MH0.sJiouIScJwPBYebHkSsRmzCPyfR5I-hRBKiOMkPgayo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});